[core]
cache_dir = ~/.cache/mopidy
config_dir = ~/.config/mopidy
data_dir = ~/.local/share/mopidy

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600

[http]
enabled = true
hostname = 127.0.0.1
port = 6680

[youtube]
enabled = true
allow_cache = true
# We use the cookie file we symlinked earlier
cookie_file = /var/lib/mopidy/.config/mopidy/cookie.txt

[file]
enabled = true
media_dirs = 
    $XDG_MUSIC_DIR|Music
    ~/Music|Music

[m3u]
enabled = true
playlists_dir = ~/.local/share/mopidy/playlists
